### ISSUE TITLE
Provide a complete example for entangled.toml

### ISSUE THREAD

**Issue by cjbarroso** [entangled/entangled.py#1]
I'm trying to enable ` .sh` to the tangler. I've had success doing this by modifying the source directly (` entangled/config/language.py`), however I'd like to do it in a more proper way. I've tried different combination of parameters in the `entangled.toml` file but I'm getting strange errors. Can we get an example config somewhere in the docs?

**Comment by jhidding** [comment]
I've added a section in the README. Better rendered documentation is in the making. BTW, getting strange errors is also an error.
