### ISSUE TITLE
Implement `entangled new` command

### ISSUE THREAD

**Issue by jhidding** [entangled/entangled.py#11]
Use `copier` to access project templates. Templates should be registered in a separate repo `entangled/template-registry`.

- [ ] `entangled new <template-name>`
- [ ] `entangled new gh:<github-url>`
- [ ] `entangled new --list-templates`

There should be a list of vetted templates inside entangled (the ones that are listed by `--list-templates`). These should contain the following info:
- template name
- template url
- description of document generator and expected environment
- prerequisites

not now:
> - [ ] design and create `entangled/template-registry` repo
>   - couples <template-name> to <github-url>
>   - cache in `${XDG_CONFIG_HOME}/entangled/template`

It may be easiest to have the registry act as a Python package installed straight from github.

Another package that also does **updating** of templates: [`copier`](https://copier.readthedocs.io).

**Comment by jhidding** [comment]
First cookiecutter template is available here: https://github.com/entangled/template-mkdocs

**Comment by OleMussmann** [comment]
What are the pre-requisites in the template list?

**Comment by jhidding** [comment]
List of software that should be available. For our own 'vetted' templates its ok to have `unsafe=True`, for others I think better not. May need to add a `--trust` flag to the `new` command for that.

> What are the pre-requisites in the template list? Do you want to have "unsafe=True" by default for copier?

**Comment by egpbos** [comment]
Bit late to the party, but: for the vetted templates, wouldn't you also want to record the vetted versions? Or do you vet only templates that you are sure will never be maliciously changed?

**Comment by jhidding** [comment]
That's a good point! That way we can have community participation with a bit of control.
