### ISSUE TITLE
end of line vs return in die configuration toml file

### ISSUE THREAD

**Issue by gerrie-myburgh** [entangled/entangled.py#53]
You need to put a <cr/lf> after the last line in the TOML config file else the code does not process the last line. An example : 

This works:

**
#required: the minimum version of Entangled
version = "2.0"            

#default watch_list is ["**/*.md"]
watch_list = ["docs/**/*.md"]

#default ignore_list is ["**/README.md"]
ignore_list = ["docs/**/*ignore.md"]

[[languages]]
name = "ts"
identifiers = ["ts"]
comment = { open = "//" }<cr/lr>
<end of file>**

This does not work:

**#required: the minimum version of Entangled
version = "2.0"            

#default watch_list is ["**/*.md"]
watch_list = ["docs/**/*.md"]

#default ignore_list is ["**/README.md"]
ignore_list = ["docs/**/*ignore.md"]

[[languages]]
name = "ts"
identifiers = ["ts"]
comment = { open = "//" }<end of file>**

**Comment by jhidding** [comment]
Thanks for this issue. That's weird. What system are you on, and what is your Python version?

**Comment by jhidding** [comment]
Closing for now, if the issue persists, please reopen.
