### ISSUE TITLE
VSCode - recognising language in code blocks

### ISSUE THREAD

**Issue by ijmitch** [entangled/entangled.py#56]
I'm a new user, so please pardon any gross ignorance!

Without the `{` after the `` ``` `` VSCode will respect the language asserted to be in the code block. This seems to be a behaviour of the built-in Markdown parsing. I couldn't find any sign of an option in VSCode's settings to change the trigger for attributes on a fence delimiter.

So `` ``` js `` has a much richer experience than `` ``` { .js ...``.

Any advice or comment?

**Comment by ijmitch** [comment]
There was a discussion thread in the Mkdocs project on a similar theme - https://github.com/mkdocs/mkdocs/discussions/3521

**Comment by ijmitch** [comment]
I also found https://github.com/microsoft/vscode/issues/157793 and https://github.com/microsoft/vscode/pull/157947 which I kinda hoped would show signs of improvement.

**Comment by jhidding** [comment]
Sorry for not replying sooner. Entangled also supports a different syntax, using Quarto style comments at the top of your code blocks.

~~~md
```js
//| id: #hello-world
...
```

or

```js
//| file: main.js

<<hello-world>>
...
~~~

This needs some settings in `entangled.toml` though:

```toml
#| file: entangled.toml
version="2.0"
watch_list=["*.md", "docs/**/*.md"]   # or whereever your files are
hooks=["quarto_attributes"]

[markers]
open="^(?P<indent>\\s*)```(?P<properties>.*)$"
close="^(?P<indent>\\s*)```\\s*$"
```

**Comment by ijmitch** [comment]
Thanks for that.

I found values for `//| id: ref` shouldn't have the leading `#`.

Also, is there any interaction between this scheme and adding custom language types?

My `entangled.toml` is now:

```
# required: the minimum version of Entangled
version = "2.0"    
hooks=["quarto_attributes"]

[markers]
open="^(?P<indent>\\s*)```(?P<properties>.*)$"
close="^(?P<indent>\\s*)```\\s*$"

[[languages]]
name = "plx"
identifiers = ["plx"]
comment = { open = "! " }
```

but a fragment beginning with:
````
```plx
//| file: text.plx

```
````
asserts 'nothing to do'.

**Comment by jhidding** [comment]
Yes! I would say `comment = {open = "!"}` without the space. Then you can do

~~~md
```plx
!| file: test.plx
...
```
~~~

**Comment by ijmitch** [comment]
Thanks for your help.
