### ISSUE TITLE
can rich be a mandatory dependency?

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [entangled/entangled.py#7]
while hacking around a bit more to warm up to the codebase 
i created https://github.com/RonnyPfannschmidt/entangled.py/pull/1/commits/120aea99314cccaa59969a62bf7f4f6d431e2a1a to enhance the file tree printing a little

seeing the code and the related code made me think that having rich always doesnt seem too bad as a dependency

im happy to submit a mr with the changes to go all in on rich if that idea sails

**Comment by jhidding** [comment]
`rich` depends on `ipywidgets`, which pulls in everything and the kitchen sink. For projects that do not involve Python otherwise this is a big ask.

**Comment by RonnyPfannschmidt** [comment]
good point, i'll check with its maintainers if something about that can be done

**Comment by RonnyPfannschmidt** [comment]
i believe that until opt-out extras land this may have to sit

**Comment by willmcgugan** [comment]
Rich doesn't depend on ipywidgets unless you request `jupyter` extras.

**Comment by jhidding** [comment]
In that case I don't object
